meta_title: "Stishly"
meta_description: "Step up your financial health with the all-in-one personal finance manager that helps you keep up to date with your budget and expenses. Sign up for free today!"
meta_image: "logo.png"
twitter_account: "@Stishly"
meta_keywords: "stishly, money, personal finance, finance tracker, budget, bill scheduler, budget calculator, money tracker"
meta_robots: "noindex, nofollow"