ui:
  transactions:
    page_length: 30
  dates:
    regex: ^[0-9]{2}-(jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)-[0-9]{4}$
  notifications:
    page_length: 30
    refresh_rate: 600000 # refresh every 10 minutes

currency_rates:
  retention: 43386 # retention rate in seconds

plans:
  free:
    cost: 0
    max_accounts: 3
    max_spending_accounts: 2
    max_schedules: 3
    max_transactions: 500
  monthly:
    cost: 600
    max_accounts: -1
    max_spending_accounts: -1
    max_schedules: -1
    max_transactions: -1
  annually:
    cost: 6000
    max_accounts: -1
    max_spending_accounts: -1
    max_schedules: -1
    max_transactions: -1