# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

#Setting.create([{ description: 'currency' }])
#Setting.create([{ description: 'date_format' }])
#Setting.create([{ description: 'first_day_ot_week' }])

Country.create({ name: "Afghanistan", date_format: "d/m/yyyy", week_start: 6 })
Country.create({ name: "Åland Islands", date_format: "yyyy-mm-dd", week_start: 1 })
Country.create({ name: "Albania", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Algeria", date_format: "dd/mm/yyyy", week_start: 6 })
Country.create({ name: "American Samoa", date_format: "mm/dd/yyyy", week_start: 1 })
Country.create({ name: "Andorra", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Angola", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Anguilla", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Antarctica", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Antigua and Barbuda", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Argentina", date_format: "dd/mm/yyyy", week_start: 0 })
Country.create({ name: "Armenia", date_format: "dd.mm.yyyy", week_start: 1 })
Country.create({ name: "Aruba", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Australia", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Austria", date_format: "d.m.yyyy", week_start: 1 })
Country.create({ name: "Azerbaijan", date_format: "dd.mm.yyyy", week_start: 1 })
Country.create({ name: "Bahamas", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Bahrain", date_format: "dd/mm/yyyy", week_start: 6 })
Country.create({ name: "Bangladesh", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Barbados", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Belarus", date_format: "dd.mm.yyyy", week_start: 1 })
Country.create({ name: "Belgium", date_format: "dd.mm.yyyy", week_start: 1 })
Country.create({ name: "Belize", date_format: "dd/mm/yyyy", week_start: 0 })
Country.create({ name: "Benin", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Bermuda", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Bhutan", date_format: "yyyy/mm/dd", week_start: 1 })
Country.create({ name: "Bolivia, Plurinational State of", date_format: "dd/mm/yyyy", week_start: 0 })
Country.create({ name: "Bonaire, Sint Eustatius and Saba", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Bosnia and Herzegovina", date_format: "d. m. yyyy", week_start: 1 })
Country.create({ name: "Botswana", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Bouvet Island", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Brazil", date_format: "dd/mm/yyyy", week_start: 0 })
Country.create({ name: "British Indian Ocean Territory", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Brunei Darussalam", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Bulgaria", date_format: "dd.mm.yyyy", week_start: 1 })
Country.create({ name: "Burkina Faso", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Burundi", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Cambodia", date_format: "dd/mm/yy", week_start: 1 })
Country.create({ name: "Cameroon", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Canada", date_format: "yyyy/mm/dd", week_start: 0 })
Country.create({ name: "Cape Verde", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Cayman Islands", date_format: "dd mmmm yyyy", week_start: 1 })
Country.create({ name: "Central African Republic", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Chad", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Chile", date_format: "dd/mm/yyyy", week_start: 0 })
Country.create({ name: "China", date_format: "yyyy-mm-dd", week_start: 0 })
Country.create({ name: "Christmas Island", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Cocos (Keeling) Islands", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Colombia", date_format: "dd/mm/yyyy", week_start: 0 })
Country.create({ name: "Comoros", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Congo", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Congo, The Democratic Republic of the", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Cook Islands", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Costa Rica", date_format: "dd/mm/yyyy", week_start: 0 })
Country.create({ name: "Côte d'Ivoire", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Croatia", date_format: "d. m. yyyy", week_start: 1 })
Country.create({ name: "Cuba", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Curaçao", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Cyprus", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Czech Republic", date_format: "d. m. yyyy", week_start: 1 })
Country.create({ name: "Denmark", date_format: "dd.mm.yyyy", week_start: 1 })
Country.create({ name: "Djibouti", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Dominica", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Dominican Republic", date_format: "dd/mm/yyyy", week_start: 0 })
Country.create({ name: "Ecuador", date_format: "dd/mm/yyyy", week_start: 0 })
Country.create({ name: "Egypt", date_format: "dd/mm/yyyy", week_start: 6 })
Country.create({ name: "El Salvador", date_format: "dd/mm/yyyy", week_start: 0 })
Country.create({ name: "Equatorial Guinea", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Eritrea", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Estonia", date_format: "dd.mm.yyyy", week_start: 1 })
Country.create({ name: "Ethiopia", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Falkland Islands (Malvinas)", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Faroe Islands", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Fiji", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Finland", date_format: "d.m.yyyy", week_start: 1 })
Country.create({ name: "France", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "French Guiana", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "French Polynesia", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "French Southern Territories", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Gabon", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Gambia", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Georgia", date_format: "dd.mm.yyyy", week_start: 1 })
Country.create({ name: "Germany", date_format: "dd-mm-yyyy", week_start: 1 })
Country.create({ name: "Ghana", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Gibraltar", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Greece", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Greenland", date_format: "d. mmm yyyy", week_start: 1 })
Country.create({ name: "Grenada", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Guadeloupe", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Guam", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Guatemala", date_format: "dd/mm/yyyy", week_start: 0 })
Country.create({ name: "Guernsey", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Guinea", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Guinea-Bissau", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Guyana", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Haiti", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Heard Island and McDonald Islands", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Holy See (Vatican City State)", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Honduras", date_format: "dd/mm/yyyy", week_start: 0 })
Country.create({ name: "Hong Kong", date_format: "d/m/yyyy", week_start: 0 })
Country.create({ name: "Hungary", date_format: "yyyy. mm. dd", week_start: 1 })
Country.create({ name: "Iceland", date_format: "dd.mm.yyyy", week_start: 1 })
Country.create({ name: "India", date_format: "dd-mm-yy", week_start: 1 })
Country.create({ name: "Indonesia", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Iran, Islamic Republic of", date_format: "yyyy/mm/dd", week_start: 6 })
Country.create({ name: "Iraq", date_format: "dd/mm/yyyy", week_start: 6 })
Country.create({ name: "Ireland", date_format: "dd-mm-yyyy", week_start: 1 })
Country.create({ name: "Isle of Man", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Israel", date_format: "dd.mm.yyyy", week_start: 0 })
Country.create({ name: "Italy", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Jamaica", date_format: "dd/mm/yyyy", week_start: 0 })
Country.create({ name: "Japan", date_format: "yyyy年mm月dd日", week_start: 0 })
Country.create({ name: "Jersey", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Jordan", date_format: "dd/mm/yyyy", week_start: 6 })
Country.create({ name: "Kazakhstan", date_format: "dd.mm.yyyy", week_start: 1 })
Country.create({ name: "Kenya", date_format: "dd mmm yyyy", week_start: 0 })
Country.create({ name: "Kiribati", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Korea, Democratic People's Republic of", date_format: "yyyy/mm/dd", week_start: 0 })
Country.create({ name: "Korea, Republic of", date_format: "yyyy/mm/dd", week_start: 0 })
Country.create({ name: "Kuwait", date_format: "dd/mm/yyyy", week_start: 6 })
Country.create({ name: "Kyrgyzstan", date_format: "dd.mm.yyyy", week_start: 1 })
Country.create({ name: "Lao People's Democratic Republic", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Latvia", date_format: "dd.mm.yyyy", week_start: 1 })
Country.create({ name: "Lebanon", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Lesotho", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Liberia", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Libya", date_format: "dd/mm/yyyy", week_start: 6 })
Country.create({ name: "Liechtenstein", date_format: "dd.mm.yyyy", week_start: 1 })
Country.create({ name: "Lithuania", date_format: "yyyy-mm-dd", week_start: 1 })
Country.create({ name: "Luxembourg", date_format: "dd.mm.yyyy", week_start: 1 })
Country.create({ name: "Macao", date_format: "dd/mm/yyyy", week_start: 0 })
Country.create({ name: "Macedonia, Republic of", date_format: "dd.mm.yyyy", week_start: 1 })
Country.create({ name: "Madagascar", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Malawi", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Malaysia", date_format: "dd mmm yyyy", week_start: 1 })
Country.create({ name: "Maldives", date_format: "yy/mm/dd", week_start: 1 })
Country.create({ name: "Mali", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Malta", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Marshall Islands", date_format: "mm/dd/yyyy", week_start: 1 })
Country.create({ name: "Martinique", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Mauritania", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Mauritius", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Mayotte", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Mexico", date_format: "dd/mm/yyyy", week_start: 0 })
Country.create({ name: "Micronesia, Federated States of", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Moldova, Republic of", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Monaco", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Mongolia", date_format: "yyyy-mm-dd", week_start: 1 })
Country.create({ name: "Montenegro", date_format: "d.m.yyyy", week_start: 1 })
Country.create({ name: "Montserrat", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Morocco", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Mozambique", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Myanmar", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Namibia", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Nauru", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Nepal", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Netherlands", date_format: "dd-mm-yyyy", week_start: 1 })
Country.create({ name: "New Caledonia", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "New Zealand", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Nicaragua", date_format: "dd/mm/yyyy", week_start: 0 })
Country.create({ name: "Niger", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Nigeria", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Niue", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Norfolk Island", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Northern Mariana Islands", date_format: "mm/dd/yyyy", week_start: 1 })
Country.create({ name: "Norway", date_format: "dd.mm.yyyy", week_start: 1 })
Country.create({ name: "Oman", date_format: "dd/mm/yyyy", week_start: 6 })
Country.create({ name: "Pakistan", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Palau", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Palestine, State of", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Panama", date_format: "dd/mm/yyyy", week_start: 0 })
Country.create({ name: "Papua New Guinea", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Paraguay", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Peru", date_format: "dd/mm/yyyy", week_start: 0 })
Country.create({ name: "Philippines", date_format: "mm/dd/yyyy", week_start: 0 })
Country.create({ name: "Pitcairn", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Poland", date_format: "dd.mm.yyyy", week_start: 1 })
Country.create({ name: "Portugal", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Puerto Rico", date_format: "mmm d, yyyy", week_start: 0 })
Country.create({ name: "Qatar", date_format: "dd/mm/yyyy", week_start: 6 })
Country.create({ name: "Réunion", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Romania", date_format: "dd.mm.yyyy", week_start: 1 })
Country.create({ name: "Russian Federation", date_format: "dd.mm.yyyy", week_start: 1 })
Country.create({ name: "Rwanda", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Saint Barthélemy", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Saint Helena, Ascension and Tristan da Cunha", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Saint Kitts and Nevis", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Saint Lucia", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Saint Martin (French part)", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Saint Pierre and Miquelon", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Saint Vincent and the Grenadines", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Samoa", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "San Marino", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Sao Tome and Principe", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Saudi Arabia", date_format: "dd/mm/yyyy", week_start: 6 })
Country.create({ name: "Senegal", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Serbia", date_format: "d.m.yyyy", week_start: 1 })
Country.create({ name: "Seychelles", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Sierra Leone", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Singapore", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Sint Maarten (Dutch part)", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Slovakia", date_format: "dd.mm.yyyy", week_start: 1 })
Country.create({ name: "Slovenia", date_format: "d. mm. yyyy", week_start: 1 })
Country.create({ name: "Solomon Islands", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Somalia", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "South Africa", date_format: "dd mmm yyyy", week_start: 0 })
Country.create({ name: "South Georgia and the South Sandwich Islands", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "South Sudan", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Spain", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Sri Lanka", date_format: "yyyy-mm-dd", week_start: 1 })
Country.create({ name: "Sudan", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Suriname", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Svalbard and Jan Mayen", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Swaziland", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Sweden", date_format: "d/m yyyy", week_start: 1 })
Country.create({ name: "Switzerland", date_format: "dd.mm.yyyy", week_start: 1 })
Country.create({ name: "Syrian Arab Republic", date_format: "dd/mm/yyyy", week_start: 6 })
Country.create({ name: "Taiwan", date_format: "yyyy/m/d", week_start: 0 })
Country.create({ name: "Tajikistan", date_format: "dd.mm.yyyy", week_start: 1 })
Country.create({ name: "Tanzania, United Republic of", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Thailand", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Timor-Leste", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Togo", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Tokelau", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Tonga", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Trinidad and Tobago", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Tunisia", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Turkey", date_format: "dd.mm.yyyy", week_start: 1 })
Country.create({ name: "Turkmenistan", date_format: "dd.mm.yyyy", week_start: 1 })
Country.create({ name: "Turks and Caicos Islands", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Tuvalu", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Uganda", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Ukraine", date_format: "dd.mm.yyyy", week_start: 1 })
Country.create({ name: "United Arab Emirates", date_format: "dd/mm/yyyy", week_start: 6 })
Country.create({ name: "United Kingdom", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "United States Minor Outlying Islands", date_format: "mm/dd/yyyy", week_start: 0 })
Country.create({ name: "United States", date_format: "mm/dd/yyyy", week_start: 0 })
Country.create({ name: "Uruguay", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Uzbekistan", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Vanuatu", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Venezuela, Bolivarian Republic of", date_format: "dd/mm/yyyy", week_start: 0 })
Country.create({ name: "Viet Nam", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Virgin Islands, British", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Virgin Islands, U.S.", date_format: "mm/dd/yyyy", week_start: 1 })
Country.create({ name: "Wallis and Futuna", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Western Sahara", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Yemen", date_format: "dd/mm/yyyy", week_start: 6 })
Country.create({ name: "Zambia", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ name: "Zimbabwe", date_format: "dd/mm/yyyy", week_start: 0 })