# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# CURRENCIES
=begin
Currency.create([{ name: 'Abkhazian apsar', symbol: '', iso_code: '', number_to_basic: 0 }])
Currency.create([{ name: 'Afghan afghani', symbol: '؋', iso_code: 'AFN', number_to_basic: 100 }])
Currency.create([{ name: 'Albanian lek', symbol: 'L', iso_code: 'ALL', number_to_basic: 100 }])
Currency.create([{ name: 'Alderney pound', symbol: '£', iso_code: '', number_to_basic: 100 }])
Currency.create([{ name: 'Algerian dinar', symbol: 'د.ج', iso_code: 'DZD', number_to_basic: 100 }])
Currency.create([{ name: 'Angolan kwanza', symbol: 'Kz', iso_code: 'AOA', number_to_basic: 100 }])
Currency.create([{ name: 'Argentine peso', symbol: '$', iso_code: 'ARS', number_to_basic: 100 }])
Currency.create([{ name: 'Armenian dram', symbol: '֏', iso_code: 'AMD', number_to_basic: 100 }])
Currency.create([{ name: 'Artsakh dram', symbol: 'դր.', iso_code: '', number_to_basic: 100 }])
Currency.create([{ name: 'Aruban florin', symbol: 'ƒ', iso_code: 'AWG', number_to_basic: 100 }])
Currency.create([{ name: 'Ascension pound', symbol: '£', iso_code: '', number_to_basic: 100 }])
Currency.create([{ name: 'Australian dollar', symbol: '$', iso_code: 'AUD', number_to_basic: 100 }])
Currency.create([{ name: 'Azerbaijani manat', symbol: '₼', iso_code: 'AZN', number_to_basic: 100 }])
Currency.create([{ name: 'Bahamian dollar', symbol: '$', iso_code: 'BSD', number_to_basic: 100 }])
Currency.create([{ name: 'Bahraini dinar', symbol: '.د.ب', iso_code: 'BHD', number_to_basic: 1000 }])
Currency.create([{ name: 'Bangladeshi taka', symbol: '৳', iso_code: 'BDT', number_to_basic: 100 }])
Currency.create([{ name: 'Barbadian dollar', symbol: '$', iso_code: 'BBD', number_to_basic: 100 }])
Currency.create([{ name: 'Belarusian ruble', symbol: 'Br', iso_code: 'BYN', number_to_basic: 100 }])
Currency.create([{ name: 'Belize dollar', symbol: '$', iso_code: 'BZD', number_to_basic: 100 }])
Currency.create([{ name: 'Bermudian dollar', symbol: '$', iso_code: 'BMD', number_to_basic: 100 }])
Currency.create([{ name: 'Bhutanese ngultrum', symbol: 'Nu.', iso_code: 'BTN', number_to_basic: 100 }])
Currency.create([{ name: 'Bolivian boliviano', symbol: 'Bs.', iso_code: 'BOB', number_to_basic: 100 }])
Currency.create([{ name: 'Bosnia and Herzegovina convertible mark', symbol: 'KM', iso_code: 'BAM', number_to_basic: 100 }])
Currency.create([{ name: 'Botswana pula', symbol: 'P', iso_code: 'BWP', number_to_basic: 100 }])
Currency.create([{ name: 'Brazilian real', symbol: 'R$', iso_code: 'BRL', number_to_basic: 100 }])
Currency.create([{ name: 'British pound', symbol: '£', iso_code: 'GBP', number_to_basic: 100 }])
Currency.create([{ name: 'British Virgin Islands dollar', symbol: '$', iso_code: '', number_to_basic: 100 }])
Currency.create([{ name: 'Brunei dollar', symbol: '$', iso_code: 'BND', number_to_basic: 100 }])
Currency.create([{ name: 'Bulgarian lev', symbol: 'лв', iso_code: 'BGN', number_to_basic: 100 }])
Currency.create([{ name: 'Burmese kyat', symbol: 'Ks', iso_code: 'MMK', number_to_basic: 100 }])
Currency.create([{ name: 'Burundian franc', symbol: 'Fr', iso_code: 'BIF', number_to_basic: 100 }])
Currency.create([{ name: 'Cambodian riel', symbol: '៛', iso_code: 'KHR', number_to_basic: 100 }])
Currency.create([{ name: 'Canadian dollar', symbol: '$', iso_code: 'CAD', number_to_basic: 100 }])
Currency.create([{ name: 'Cape Verdean escudo', symbol: '$', iso_code: 'CVE', number_to_basic: 100 }])
Currency.create([{ name: 'Cayman Islands dollar', symbol: '$', iso_code: 'KYD', number_to_basic: 100 }])
Currency.create([{ name: 'Central African CFA franc', symbol: 'Fr', iso_code: 'XAF', number_to_basic: 100 }])
Currency.create([{ name: 'CFP franc', symbol: 'Fr', iso_code: 'XPF', number_to_basic: 100 }])
Currency.create([{ name: 'Chilean peso', symbol: '$', iso_code: 'CLP', number_to_basic: 100 }])
Currency.create([{ name: 'Chinese yuan', symbol: '元', iso_code: 'CNY', number_to_basic: 100 }])
Currency.create([{ name: 'Colombian peso', symbol: '$', iso_code: 'COP', number_to_basic: 100 }])
Currency.create([{ name: 'Comorian franc', symbol: 'Fr', iso_code: 'KMF', number_to_basic: 100 }])
Currency.create([{ name: 'Congolese franc', symbol: 'Fr', iso_code: 'CDF', number_to_basic: 100 }])
Currency.create([{ name: 'Cook Islands dollar', symbol: '$', iso_code: '', number_to_basic: 100 }])
Currency.create([{ name: 'Costa Rican colón', symbol: '₡', iso_code: 'CRC', number_to_basic: 100 }])
Currency.create([{ name: 'Croatian kuna', symbol: 'kn', iso_code: 'HRK', number_to_basic: 100 }])
Currency.create([{ name: 'Cuban convertible peso', symbol: '$', iso_code: 'CUC', number_to_basic: 100 }])
Currency.create([{ name: 'Cuban peso', symbol: '$', iso_code: 'CUP', number_to_basic: 100 }])
Currency.create([{ name: 'Czech koruna', symbol: 'Kč', iso_code: 'CZK', number_to_basic: 100 }])
Currency.create([{ name: 'Danish krone', symbol: 'kr', iso_code: 'DKK', number_to_basic: 100 }])
Currency.create([{ name: 'Djiboutian franc', symbol: 'Fr', iso_code: 'DJF', number_to_basic: 100 }])
Currency.create([{ name: 'Dominican peso', symbol: '$', iso_code: 'DOP', number_to_basic: 100 }])
Currency.create([{ name: 'Eastern Caribbean dollar', symbol: '$', iso_code: 'XCD', number_to_basic: 100 }])
Currency.create([{ name: 'Egyptian pound', symbol: '£', iso_code: 'EGP', number_to_basic: 100 }])
Currency.create([{ name: 'Eritrean nakfa', symbol: 'Nfk', iso_code: 'ERN', number_to_basic: 100 }])
Currency.create([{ name: 'Ethiopian birr', symbol: 'Br', iso_code: 'ETB', number_to_basic: 100 }])
Currency.create([{ name: 'Euro', symbol: '€', iso_code: 'EUR', number_to_basic: 100 }])
Currency.create([{ name: 'Falkland Islands pound', symbol: '£', iso_code: 'FKP', number_to_basic: 100 }])
Currency.create([{ name: 'Faroese króna', symbol: 'kr', iso_code: '', number_to_basic: 100 }])
Currency.create([{ name: 'Fijian dollar', symbol: '$', iso_code: 'FJD', number_to_basic: 100 }])
Currency.create([{ name: 'Gambian dalasi', symbol: 'D', iso_code: 'GMD', number_to_basic: 100 }])
Currency.create([{ name: 'Georgian lari', symbol: '₾', iso_code: 'GEL', number_to_basic: 100 }])
Currency.create([{ name: 'Ghanaian cedi', symbol: '₵', iso_code: 'GHS', number_to_basic: 100 }])
Currency.create([{ name: 'Gibraltar pound', symbol: '£', iso_code: 'GIP', number_to_basic: 100 }])
Currency.create([{ name: 'Guatemalan quetzal', symbol: 'Q', iso_code: 'GTQ', number_to_basic: 100 }])
Currency.create([{ name: 'Guernsey pound', symbol: '£', iso_code: 'GGP[G]', number_to_basic: 100 }])
Currency.create([{ name: 'Guinean franc', symbol: 'Fr', iso_code: 'GNF', number_to_basic: 100 }])
Currency.create([{ name: 'Guyanese dollar', symbol: '$', iso_code: 'GYD', number_to_basic: 100 }])
Currency.create([{ name: 'Haitian gourde', symbol: 'G', iso_code: 'HTG', number_to_basic: 100 }])
Currency.create([{ name: 'Honduran lempira', symbol: 'L', iso_code: 'HNL', number_to_basic: 100 }])
Currency.create([{ name: 'Hong Kong dollar', symbol: '$', iso_code: 'HKD', number_to_basic: 100 }])
Currency.create([{ name: 'Hungarian forint', symbol: 'Ft', iso_code: 'HUF', number_to_basic: 100 }])
Currency.create([{ name: 'Icelandic króna', symbol: 'kr', iso_code: 'ISK', number_to_basic: 100 }])
Currency.create([{ name: 'Indian rupee', symbol: '₹', iso_code: 'INR', number_to_basic: 100 }])
Currency.create([{ name: 'Indonesian rupiah', symbol: 'Rp', iso_code: 'IDR', number_to_basic: 100 }])
Currency.create([{ name: 'Iranian rial', symbol: '﷼', iso_code: 'IRR', number_to_basic: 100 }])
Currency.create([{ name: 'Iraqi dinar', symbol: 'ع.د', iso_code: 'IQD', number_to_basic: 1000 }])
Currency.create([{ name: 'Israeli new shekel', symbol: '₪', iso_code: 'ILS', number_to_basic: 100 }])
Currency.create([{ name: 'Jamaican dollar', symbol: '$', iso_code: 'JMD', number_to_basic: 100 }])
Currency.create([{ name: 'Japanese yen', symbol: '¥', iso_code: 'JPY', number_to_basic: 0 }])
Currency.create([{ name: 'Jersey pound', symbol: '£', iso_code: 'JEP[G]', number_to_basic: 100 }])
Currency.create([{ name: 'Jordanian dinar', symbol: 'د.ا', iso_code: 'JOD', number_to_basic: 100 }])
Currency.create([{ name: 'Kazakhstani tenge', symbol: '₸', iso_code: 'KZT', number_to_basic: 100 }])
Currency.create([{ name: 'Kenyan shilling', symbol: 'Sh', iso_code: 'KES', number_to_basic: 100 }])
Currency.create([{ name: 'Kiribati dollar', symbol: '$', iso_code: 'KID', number_to_basic: 100 }])
Currency.create([{ name: 'Kuwaiti dinar', symbol: 'د.ك', iso_code: 'KWD', number_to_basic: 1000 }])
Currency.create([{ name: 'Kyrgyzstani som', symbol: 'с', iso_code: 'KGS', number_to_basic: 100 }])
Currency.create([{ name: 'Lao kip', symbol: '₭', iso_code: 'LAK', number_to_basic: 100 }])
Currency.create([{ name: 'Lebanese pound', symbol: 'ل.ل', iso_code: 'LBP', number_to_basic: 100 }])
Currency.create([{ name: 'Lesotho loti', symbol: 'L', iso_code: 'LSL', number_to_basic: 100 }])
Currency.create([{ name: 'Liberian dollar', symbol: '$', iso_code: 'LRD', number_to_basic: 100 }])
Currency.create([{ name: 'Libyan dinar', symbol: 'ل.د', iso_code: 'LYD', number_to_basic: 1000 }])
Currency.create([{ name: 'Macanese pataca', symbol: 'P', iso_code: 'MOP', number_to_basic: 100 }])
Currency.create([{ name: 'Macedonian denar', symbol: 'ден', iso_code: 'MKD', number_to_basic: 100 }])
Currency.create([{ name: 'Malagasy ariary', symbol: 'Ar', iso_code: 'MGA', number_to_basic: 5 }])
Currency.create([{ name: 'Malawian kwacha', symbol: 'MK', iso_code: 'MWK', number_to_basic: 100 }])
Currency.create([{ name: 'Malaysian ringgit', symbol: 'RM', iso_code: 'MYR', number_to_basic: 100 }])
Currency.create([{ name: 'Maldivian rufiyaa', symbol: '.ރ', iso_code: 'MVR', number_to_basic: 100 }])
Currency.create([{ name: 'Manx pound', symbol: '£', iso_code: 'IMP[G]', number_to_basic: 100 }])
Currency.create([{ name: 'Mauritanian ouguiya', symbol: 'UM', iso_code: 'MRU', number_to_basic: 5 }])
Currency.create([{ name: 'Mauritian rupee', symbol: '₨', iso_code: 'MUR', number_to_basic: 100 }])
Currency.create([{ name: 'Mexican peso', symbol: '$', iso_code: 'MXN', number_to_basic: 100 }])
Currency.create([{ name: 'Micronesian dollar', symbol: '$', iso_code: '', number_to_basic: 100 }])
Currency.create([{ name: 'Moldovan leu', symbol: 'L', iso_code: 'MDL', number_to_basic: 100 }])
Currency.create([{ name: 'Mongolian tögrög', symbol: '₮', iso_code: 'MNT', number_to_basic: 100 }])
Currency.create([{ name: 'Moroccan dirham', symbol: 'د.م.', iso_code: 'MAD', number_to_basic: 100 }])
Currency.create([{ name: 'Mozambican metical', symbol: 'MT', iso_code: 'MZN', number_to_basic: 100 }])
Currency.create([{ name: 'Namibian dollar', symbol: '$', iso_code: 'NAD', number_to_basic: 100 }])
Currency.create([{ name: 'Nauruan dollar', symbol: '$', iso_code: '', number_to_basic: 100 }])
Currency.create([{ name: 'Nepalese rupee', symbol: '₨', iso_code: 'NPR', number_to_basic: 100 }])
Currency.create([{ name: 'Netherlands Antillean guilder', symbol: 'ƒ', iso_code: 'ANG', number_to_basic: 100 }])
Currency.create([{ name: 'New Taiwan dollar', symbol: '$', iso_code: 'TWD', number_to_basic: 100 }])
Currency.create([{ name: 'New Zealand dollar', symbol: '$', iso_code: 'NZD', number_to_basic: 100 }])
Currency.create([{ name: 'Nicaraguan córdoba', symbol: 'C$', iso_code: 'NIO', number_to_basic: 100 }])
Currency.create([{ name: 'Nigerian naira', symbol: '₦', iso_code: 'NGN', number_to_basic: 100 }])
Currency.create([{ name: 'Niue dollar', symbol: '$', iso_code: '', number_to_basic: 100 }])
Currency.create([{ name: 'North Korean won', symbol: '₩', iso_code: 'KPW', number_to_basic: 100 }])
Currency.create([{ name: 'Norwegian krone', symbol: 'kr', iso_code: 'NOK', number_to_basic: 100 }])
Currency.create([{ name: 'Omani rial', symbol: 'ر.ع.', iso_code: 'OMR', number_to_basic: 1000 }])
Currency.create([{ name: 'Pakistani rupee', symbol: '₨', iso_code: 'PKR', number_to_basic: 100 }])
Currency.create([{ name: 'Palauan dollar', symbol: '$', iso_code: '', number_to_basic: 100 }])
Currency.create([{ name: 'Panamanian balboa', symbol: 'B/.', iso_code: 'PAB', number_to_basic: 100 }])
Currency.create([{ name: 'Papua New Guinean kina', symbol: 'K', iso_code: 'PGK', number_to_basic: 100 }])
Currency.create([{ name: 'Paraguayan guaraní', symbol: '₲', iso_code: 'PYG', number_to_basic: 100 }])
Currency.create([{ name: 'Peruvian sol', symbol: 'S/.', iso_code: 'PEN', number_to_basic: 100 }])
Currency.create([{ name: 'Philippine piso', symbol: '₱', iso_code: 'PHP', number_to_basic: 100 }])
Currency.create([{ name: 'Pitcairn Islands dollar', symbol: '$', iso_code: '', number_to_basic: 100 }])
Currency.create([{ name: 'Polish złoty', symbol: 'zł', iso_code: 'PLN', number_to_basic: 100 }])
Currency.create([{ name: 'Qatari riyal', symbol: 'ر.ق', iso_code: 'QAR', number_to_basic: 100 }])
Currency.create([{ name: 'Romanian leu', symbol: 'lei', iso_code: 'RON', number_to_basic: 100 }])
Currency.create([{ name: 'Russian ruble', symbol: '₽', iso_code: 'RUB', number_to_basic: 100 }])
Currency.create([{ name: 'Rwandan franc', symbol: 'Fr', iso_code: 'RWF', number_to_basic: 100 }])
Currency.create([{ name: 'Sahrawi peseta', symbol: '₧', iso_code: '', number_to_basic: 100 }])
Currency.create([{ name: 'Saint Helena pound', symbol: '£', iso_code: 'SHP', number_to_basic: 100 }])
Currency.create([{ name: 'Samoan tālā', symbol: 'T', iso_code: 'WST', number_to_basic: 100 }])
Currency.create([{ name: 'São Tomé and Príncipe dobra', symbol: 'Db', iso_code: 'STN', number_to_basic: 100 }])
Currency.create([{ name: 'Saudi riyal', symbol: 'ر.س', iso_code: 'SAR', number_to_basic: 100 }])
Currency.create([{ name: 'Serbian dinar', symbol: 'дин', iso_code: 'RSD', number_to_basic: 100 }])
Currency.create([{ name: 'Seychellois rupee', symbol: '₨', iso_code: 'SCR', number_to_basic: 100 }])
Currency.create([{ name: 'Sierra Leonean leone', symbol: 'Le', iso_code: 'SLL', number_to_basic: 100 }])
Currency.create([{ name: 'Singapore dollar', symbol: '$', iso_code: 'SGD', number_to_basic: 100 }])
Currency.create([{ name: 'Solomon Islands dollar', symbol: '$', iso_code: 'SBD', number_to_basic: 100 }])
Currency.create([{ name: 'Somali shilling', symbol: 'Sh', iso_code: 'SOS', number_to_basic: 100 }])
Currency.create([{ name: 'Somaliland shilling', symbol: 'Sl', iso_code: '', number_to_basic: 100 }])
Currency.create([{ name: 'South African rand', symbol: 'R', iso_code: 'ZAR', number_to_basic: 100 }])
Currency.create([{ name: 'South Georgia and the South Sandwich Islands pound', symbol: '£', iso_code: '', number_to_basic: 100 }])
Currency.create([{ name: 'South Korean won', symbol: '₩', iso_code: 'KRW', number_to_basic: 100 }])
Currency.create([{ name: 'South Sudanese pound', symbol: '£', iso_code: 'SSP', number_to_basic: 100 }])
Currency.create([{ name: 'Sri Lankan rupee', symbol: 'Rs', iso_code: 'LKR', number_to_basic: 100 }])
Currency.create([{ name: 'Sudanese pound', symbol: 'ج.س.', iso_code: 'SDG', number_to_basic: 100 }])
Currency.create([{ name: 'Surinamese dollar', symbol: '$', iso_code: 'SRD', number_to_basic: 100 }])
Currency.create([{ name: 'Swazi lilangeni', symbol: 'L', iso_code: 'SZL', number_to_basic: 100 }])
Currency.create([{ name: 'Swedish krona', symbol: 'kr', iso_code: 'SEK', number_to_basic: 100 }])
Currency.create([{ name: 'Swiss franc', symbol: 'Fr', iso_code: 'CHF', number_to_basic: 100 }])
Currency.create([{ name: 'Syrian pound', symbol: '£', iso_code: 'SYP', number_to_basic: 100 }])
Currency.create([{ name: 'Tajikistani somoni', symbol: 'ЅМ', iso_code: 'TJS', number_to_basic: 100 }])
Currency.create([{ name: 'Tanzanian shilling', symbol: 'Sh', iso_code: 'TZS', number_to_basic: 100 }])
Currency.create([{ name: 'Thai baht', symbol: '฿', iso_code: 'THB', number_to_basic: 100 }])
Currency.create([{ name: 'Tongan paʻanga', symbol: 'T$', iso_code: 'TOP', number_to_basic: 100 }])
Currency.create([{ name: 'Transnistrian ruble', symbol: 'р.', iso_code: 'PRB[G]', number_to_basic: 100 }])
Currency.create([{ name: 'Trinidad and Tobago dollar', symbol: '$', iso_code: 'TTD', number_to_basic: 100 }])
Currency.create([{ name: 'Tristan da Cunha pound', symbol: '£', iso_code: '', number_to_basic: 100 }])
Currency.create([{ name: 'Tunisian dinar', symbol: 'د.ت', iso_code: 'TND', number_to_basic: 1000 }])
Currency.create([{ name: 'Turkish lira', symbol: '₺', iso_code: 'TRY', number_to_basic: 100 }])
Currency.create([{ name: 'Turkmenistan manat', symbol: 'm', iso_code: 'TMT', number_to_basic: 100 }])
Currency.create([{ name: 'Tuvaluan dollar', symbol: '$', iso_code: 'TVD[G]', number_to_basic: 100 }])
Currency.create([{ name: 'Ugandan shilling', symbol: 'Sh', iso_code: 'UGX', number_to_basic: 100 }])
Currency.create([{ name: 'Ukrainian hryvnia', symbol: '₴', iso_code: 'UAH', number_to_basic: 100 }])
Currency.create([{ name: 'United Arab Emirates dirham', symbol: 'د.إ', iso_code: 'AED', number_to_basic: 100 }])
Currency.create([{ name: 'United States dollar', symbol: '$', iso_code: 'USD', number_to_basic: 100 }])
Currency.create([{ name: 'Uruguayan peso', symbol: '$', iso_code: 'UYU', number_to_basic: 100 }])
Currency.create([{ name: 'Uzbekistani so\'m', symbol: 'so\'m', iso_code: 'UZS', number_to_basic: 100 }])
Currency.create([{ name: 'Vanuatu vatu', symbol: 'Vt', iso_code: 'VUV', number_to_basic: 0 }])
Currency.create([{ name: 'Venezuelan bolívar soberano', symbol: 'Bs.', iso_code: 'VES', number_to_basic: 100 }])
Currency.create([{ name: 'Vietnamese đồng', symbol: '₫', iso_code: 'VND', number_to_basic: 10 }])
Currency.create([{ name: 'West African CFA franc', symbol: 'Fr', iso_code: 'XOF', number_to_basic: 100 }])
Currency.create([{ name: 'Yemeni rial', symbol: '﷼', iso_code: 'YER', number_to_basic: 100 }])
Currency.create([{ name: 'Zambian kwacha', symbol: 'ZK', iso_code: 'ZMW', number_to_basic: 100 }])
=end
# COUNTRIES
Country.create([{ name: 'Afghanistan', currency_id: 2, date_format: 'DMY', week_start: 'Mon' }])
Country.create!([{ name: 'Albania', currency_id: 3, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Algeria', currency_id: 5, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Andorra', currency_id: 56, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Angola', currency_id: 6, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Antigua and Barbuda', currency_id: 52, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Argentina', currency_id: 7, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Armenia', currency_id: 8, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Australia', currency_id: 12, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Austria', currency_id: 56, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Azerbaijan', currency_id: 13, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'The Bahamas', currency_id: 56, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Bahrain', currency_id: 15, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Bangladesh', currency_id: 16, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Barbados', currency_id: 17, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Belarus', currency_id: 18, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Belgium', currency_id: 56, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Belize', currency_id: 19, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Benin', currency_id: 175, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Bhutan', currency_id: 73, date_format: 'YMD', week_start: 'Mon' }])
Country.create([{ name: 'Bolivia', currency_id: 22, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Bosnia and Herzegovina', currency_id: 23, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Botswana', currency_id: 24, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Brazil', currency_id: 25, date_format: 'DMY', week_start: 'Sun' }])
Country.create([{ name: 'Brunei', currency_id: 28, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Bulgaria', currency_id: 29, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Burkina Faso', currency_id: 175, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Burundi', currency_id: 31, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Cabo Verde', currency_id: 34, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Cambodia', currency_id: 32, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Cameroon', currency_id: 36, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Canada', currency_id: 33, date_format: 'DMY', week_start: 'Sun' }])
Country.create([{ name: 'Central African Republic', currency_id: 36, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Chad', currency_id: 36, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Chile', currency_id: 38, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'China', currency_id: 39, date_format: 'YMD', week_start: 'Mon' }])
Country.create([{ name: 'Colombia', currency_id: 40, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Comoros', currency_id: 41, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Congo, Democratic Republic of the', currency_id: 42, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Congo, Republic of the', currency_id: 42, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Costa Rica', currency_id: 44, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Côte d’Ivoire', currency_id: 175, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Croatia', currency_id: 45, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Cuba', currency_id: 47, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Cyprus', currency_id: 56, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Czech Republic', currency_id: 48, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Denmark', currency_id: 49, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Djibouti', currency_id: 50, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Dominica', currency_id: 52, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Dominican Republic', currency_id: 51, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'East Timor (Timor-Leste)', currency_id: 169, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Ecuador', currency_id: 169, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Egypt', currency_id: 53, date_format: 'DMY', week_start: 'Sun' }])
Country.create([{ name: 'El Salvador', currency_id: 169, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Equatorial Guinea', currency_id: 36, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Eritrea', currency_id: 54, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Estonia', currency_id: 56, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Ethiopia', currency_id: 55, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Fiji', currency_id: 59, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Finland', currency_id: 56, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'France', currency_id: 56, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Gabon', currency_id: 36, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'The Gambia', currency_id: 60, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Georgia', currency_id: 61, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Germany', currency_id: 56, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Ghana', currency_id: 62, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Greece', currency_id: 56, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Grenada', currency_id: 52, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Guatemala', currency_id: 64, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Guinea', currency_id: 66, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Guinea-Bissau', currency_id: 175, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Guyana', currency_id: 67, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Haiti', currency_id: 68, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Honduras', currency_id: 69, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Hungary', currency_id: 71, date_format: 'YMD', week_start: 'Mon' }])
Country.create([{ name: 'Iceland', currency_id: 72, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'India', currency_id: 73, date_format: 'DMY', week_start: 'Sun' }])
Country.create([{ name: 'Indonesia', currency_id: 74, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Iran', currency_id: 75, date_format: 'YMD', week_start: 'Mon' }])
Country.create([{ name: 'Iraq', currency_id: 76, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Ireland', currency_id: 56, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Israel', currency_id: 77, date_format: 'DMY', week_start: 'Sun' }])
Country.create([{ name: 'Italy', currency_id: 56, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Jamaica', currency_id: 78, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Japan', currency_id: 79, date_format: 'YMD', week_start: 'Sun' }])
Country.create([{ name: 'Jordan', currency_id: 81, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Kazakhstan', currency_id: 82, date_format: 'YDM', week_start: 'Mon' }])
Country.create([{ name: 'Kenya', currency_id: 83, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Kiribati', currency_id: 84, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Korea, North', currency_id: 116, date_format: 'YMD', week_start: 'Mon' }])
Country.create([{ name: 'Korea, South', currency_id: 146, date_format: 'YMD', week_start: 'Mon' }])
Country.create([{ name: 'Kosovo', currency_id: 56, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Kuwait', currency_id: 85, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Kyrgyzstan', currency_id: 86, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Laos', currency_id: 87, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Latvia', currency_id: 56, date_format: 'YDM', week_start: 'Mon' }])
Country.create([{ name: 'Lebanon', currency_id: 88, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Lesotho', currency_id: 89, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Liberia', currency_id: 90, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Libya', currency_id: 91, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Liechtenstein', currency_id: 153, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Lithuania', currency_id: 56, date_format: 'YMD', week_start: 'Mon' }])
Country.create([{ name: 'Luxembourg', currency_id: 56, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Macedonia', currency_id: 93, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Madagascar', currency_id: 94, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Malawi', currency_id: 95, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Malaysia', currency_id: 96, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Maldives', currency_id: 97, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Mali', currency_id: 175, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Malta', currency_id: 56, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Marshall Islands', currency_id: 169, date_format: 'MDY', week_start: 'Mon' }])
Country.create([{ name: 'Mauritania', currency_id: 99, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Mauritius', currency_id: 100, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Mexico', currency_id: 101, date_format: 'DMY', week_start: 'Sun' }])
Country.create([{ name: 'Micronesia, Federated States of', currency_id: 169, date_format: 'MDY', week_start: 'Mon' }])
Country.create([{ name: 'Moldova', currency_id: 103, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Monaco', currency_id: 56, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Mongolia', currency_id: 104, date_format: 'YMD', week_start: 'Mon' }])
Country.create([{ name: 'Montenegro', currency_id: 56, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Morocco', currency_id: 105, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Mozambique', currency_id: 106, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Myanmar (Burma)', currency_id: 30, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Namibia', currency_id: 107, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Nauru', currency_id: 12, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Nepal', currency_id: 109, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Netherlands', currency_id: 56, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Netherlands Antilles', currency_id: 110, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'New Zealand', currency_id: 112, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Nicaragua', currency_id: 113, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Niger', currency_id: 175, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Nigeria', currency_id: 114, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Northern Ireland', currency_id: 26, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Norway', currency_id: 117, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Oman', currency_id: 118, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Pakistan', currency_id: 119, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Palau', currency_id: 169, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Panama', currency_id: 121, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Papua New Guinea', currency_id: 122, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Paraguay', currency_id: 123, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Peru', currency_id: 124, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Philippines', currency_id: 125, date_format: 'DMY', week_start: 'Sun' }])
Country.create([{ name: 'Poland', currency_id: 127, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Portugal', currency_id: 56, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Qatar', currency_id: 128, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Romania', currency_id: 129, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Russia', currency_id: 130, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Rwanda', currency_id: 131, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Saint Kitts and Nevis', currency_id: 52, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Saint Lucia', currency_id: 52, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Saint Vincent and the Grenadines', currency_id: 52, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Samoa', currency_id: 134, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'San Marino', currency_id: 56, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Sao Tome and Principe', currency_id: 135, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Saudi Arabia', currency_id: 136, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Scotland', currency_id: 26, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Senegal', currency_id: 175, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Serbia', currency_id: 137, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Seychelles', currency_id: 138, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Sierra Leone', currency_id: 139, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Singapore', currency_id: 140, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Slovakia', currency_id: 56, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Slovenia', currency_id: 56, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Solomon Islands', currency_id: 141, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Somalia', currency_id: 142, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'South Africa', currency_id: 144, date_format: 'DMY', week_start: 'Sun' }])
Country.create([{ name: 'Spain', currency_id: 56, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Sri Lanka', currency_id: 148, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Sudan', currency_id: 149, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Sudan, South', currency_id: 147, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Suriname', currency_id: 150, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Swaziland', currency_id: 151, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Sweden', currency_id: 152, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Switzerland', currency_id: 153, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Syria', currency_id: 154, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Taiwan', currency_id: 111, date_format: 'YMD', week_start: 'Sun' }])
Country.create([{ name: 'Tajikistan', currency_id: 155, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Tanzania', currency_id: 156, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Thailand', currency_id: 157, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Togo', currency_id: 175, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Tonga', currency_id: 158, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Trinidad and Tobago', currency_id: 160, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Tunisia', currency_id: 162, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Turkey', currency_id: 163, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Turkmenistan', currency_id: 164, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Tuvalu', currency_id: 165, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Uganda', currency_id: 166, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Ukraine', currency_id: 167, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'United Arab Emirates', currency_id: 168, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'United Kingdom', currency_id: 26, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'United States', currency_id: 169, date_format: 'MDY', week_start: 'Sun' }])
Country.create([{ name: 'Uruguay', currency_id: 170, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Uzbekistan', currency_id: 171, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Vanuatu', currency_id: 172, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Vatican City', currency_id: 56, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Venezuela', currency_id: 173, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Vietnam', currency_id: 174, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Wales', currency_id: 26, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Yemen', currency_id: 176, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Zambia', currency_id: 177, date_format: 'DMY', week_start: 'Mon' }])
Country.create([{ name: 'Zimbabwe', currency_id: 169, date_format: 'DMY', week_start: 'Mon' }])