# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

#Setting.create([{ description: 'currency' }])
#Setting.create([{ description: 'date_format' }])
#Setting.create([{ description: 'first_day_ot_week' }])

Country.create({ country_code: "AF", name: "Afghanistan", date_format: "d/m/yyyy", week_start: 6 })
Country.create({ country_code: "AX", name: "Åland Islands", date_format: "yyyy-mm-dd", week_start: 1 })
Country.create({ country_code: "AL", name: "Albania", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "DZ", name: "Algeria", date_format: "dd/mm/yyyy", week_start: 6 })
Country.create({ country_code: "AS", name: "American Samoa", date_format: "mm/dd/yyyy", week_start: 1 })
Country.create({ country_code: "AD", name: "Andorra", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "AO", name: "Angola", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "AI", name: "Anguilla", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "AQ", name: "Antarctica", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "AG", name: "Antigua and Barbuda", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "AR", name: "Argentina", date_format: "dd/mm/yyyy", week_start: 0 })
Country.create({ country_code: "AM", name: "Armenia", date_format: "dd.mm.yyyy", week_start: 1 })
Country.create({ country_code: "AW", name: "Aruba", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "AU", name: "Australia", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "AT", name: "Austria", date_format: "d.m.yyyy", week_start: 1 })
Country.create({ country_code: "AZ", name: "Azerbaijan", date_format: "dd.mm.yyyy", week_start: 1 })
Country.create({ country_code: "BS", name: "Bahamas", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "BH", name: "Bahrain", date_format: "dd/mm/yyyy", week_start: 6 })
Country.create({ country_code: "BD", name: "Bangladesh", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "BB", name: "Barbados", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "BY", name: "Belarus", date_format: "dd.mm.yyyy", week_start: 1 })
Country.create({ country_code: "BE", name: "Belgium", date_format: "dd.mm.yyyy", week_start: 1 })
Country.create({ country_code: "BZ", name: "Belize", date_format: "dd/mm/yyyy", week_start: 0 })
Country.create({ country_code: "BJ", name: "Benin", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "BM", name: "Bermuda", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "BT", name: "Bhutan", date_format: "yyyy/mm/dd", week_start: 1 })
Country.create({ country_code: "BO", name: "Bolivia, Plurinational State of", date_format: "dd/mm/yyyy", week_start: 0 })
Country.create({ country_code: "BQ", name: "Bonaire, Sint Eustatius and Saba", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "BA", name: "Bosnia and Herzegovina", date_format: "d. m. yyyy", week_start: 1 })
Country.create({ country_code: "BW", name: "Botswana", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "BV", name: "Bouvet Island", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "BR", name: "Brazil", date_format: "dd/mm/yyyy", week_start: 0 })
Country.create({ country_code: "IO", name: "British Indian Ocean Territory", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "BN", name: "Brunei Darussalam", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "BG", name: "Bulgaria", date_format: "dd.mm.yyyy", week_start: 1 })
Country.create({ country_code: "BF", name: "Burkina Faso", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "BI", name: "Burundi", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "KH", name: "Cambodia", date_format: "dd/mm/yy", week_start: 1 })
Country.create({ country_code: "CM", name: "Cameroon", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "CA", name: "Canada", date_format: "yyyy/mm/dd", week_start: 0 })
Country.create({ country_code: "CV", name: "Cape Verde", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "KY", name: "Cayman Islands", date_format: "dd mmmm yyyy", week_start: 1 })
Country.create({ country_code: "CF", name: "Central African Republic", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "TD", name: "Chad", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "CL", name: "Chile", date_format: "dd/mm/yyyy", week_start: 0 })
Country.create({ country_code: "CN", name: "China", date_format: "yyyy-mm-dd", week_start: 0 })
Country.create({ country_code: "CX", name: "Christmas Island", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "CC", name: "Cocos (Keeling) Islands", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "CO", name: "Colombia", date_format: "dd/mm/yyyy", week_start: 0 })
Country.create({ country_code: "KM", name: "Comoros", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "CG", name: "Congo", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "CD", name: "Congo, The Democratic Republic of the", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "CK", name: "Cook Islands", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "CR", name: "Costa Rica", date_format: "dd/mm/yyyy", week_start: 0 })
Country.create({ country_code: "CI", name: "Côte d'Ivoire", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "HR", name: "Croatia", date_format: "d. m. yyyy", week_start: 1 })
Country.create({ country_code: "CU", name: "Cuba", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "CW", name: "Curaçao", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "CY", name: "Cyprus", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "CZ", name: "Czech Republic", date_format: "d. m. yyyy", week_start: 1 })
Country.create({ country_code: "DK", name: "Denmark", date_format: "dd.mm.yyyy", week_start: 1 })
Country.create({ country_code: "DJ", name: "Djibouti", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "DM", name: "Dominica", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "DO", name: "Dominican Republic", date_format: "dd/mm/yyyy", week_start: 0 })
Country.create({ country_code: "EC", name: "Ecuador", date_format: "dd/mm/yyyy", week_start: 0 })
Country.create({ country_code: "EG", name: "Egypt", date_format: "dd/mm/yyyy", week_start: 6 })
Country.create({ country_code: "SV", name: "El Salvador", date_format: "dd/mm/yyyy", week_start: 0 })
Country.create({ country_code: "GQ", name: "Equatorial Guinea", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "ER", name: "Eritrea", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "EE", name: "Estonia", date_format: "dd.mm.yyyy", week_start: 1 })
Country.create({ country_code: "ET", name: "Ethiopia", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "FK", name: "Falkland Islands (Malvinas)", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "FO", name: "Faroe Islands", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "FJ", name: "Fiji", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "FI", name: "Finland", date_format: "d.m.yyyy", week_start: 1 })
Country.create({ country_code: "FR", name: "France", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "GF", name: "French Guiana", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "PF", name: "French Polynesia", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "TF", name: "French Southern Territories", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "GA", name: "Gabon", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "GM", name: "Gambia", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "GE", name: "Georgia", date_format: "dd.mm.yyyy", week_start: 1 })
Country.create({ country_code: "DE", name: "Germany", date_format: "dd-mm-yyyy", week_start: 1 })
Country.create({ country_code: "GH", name: "Ghana", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "GI", name: "Gibraltar", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "GR", name: "Greece", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "GL", name: "Greenland", date_format: "d. mmm yyyy", week_start: 1 })
Country.create({ country_code: "GD", name: "Grenada", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "GP", name: "Guadeloupe", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "GU", name: "Guam", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "GT", name: "Guatemala", date_format: "dd/mm/yyyy", week_start: 0 })
Country.create({ country_code: "GG", name: "Guernsey", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "GN", name: "Guinea", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "GW", name: "Guinea-Bissau", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "GY", name: "Guyana", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "HT", name: "Haiti", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "HM", name: "Heard Island and McDonald Islands", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "VA", name: "Holy See (Vatican City State)", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "HN", name: "Honduras", date_format: "dd/mm/yyyy", week_start: 0 })
Country.create({ country_code: "HK", name: "Hong Kong", date_format: "d/m/yyyy", week_start: 0 })
Country.create({ country_code: "HU", name: "Hungary", date_format: "yyyy. mm. dd", week_start: 1 })
Country.create({ country_code: "IS", name: "Iceland", date_format: "dd.mm.yyyy", week_start: 1 })
Country.create({ country_code: "IN", name: "India", date_format: "dd-mm-yy", week_start: 1 })
Country.create({ country_code: "ID", name: "Indonesia", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "IR", name: "Iran, Islamic Republic of", date_format: "yyyy/mm/dd", week_start: 6 })
Country.create({ country_code: "IQ", name: "Iraq", date_format: "dd/mm/yyyy", week_start: 6 })
Country.create({ country_code: "IE", name: "Ireland", date_format: "dd-mm-yyyy", week_start: 1 })
Country.create({ country_code: "IM", name: "Isle of Man", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "IL", name: "Israel", date_format: "dd.mm.yyyy", week_start: 0 })
Country.create({ country_code: "IT", name: "Italy", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "JM", name: "Jamaica", date_format: "dd/mm/yyyy", week_start: 0 })
Country.create({ country_code: "JP", name: "Japan", date_format: "yyyy年mm月dd日", week_start: 0 })
Country.create({ country_code: "JE", name: "Jersey", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "JO", name: "Jordan", date_format: "dd/mm/yyyy", week_start: 6 })
Country.create({ country_code: "KZ", name: "Kazakhstan", date_format: "dd.mm.yyyy", week_start: 1 })
Country.create({ country_code: "KE", name: "Kenya", date_format: "dd mmm yyyy", week_start: 0 })
Country.create({ country_code: "KI", name: "Kiribati", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "KP", name: "Korea, Democratic People's Republic of", date_format: "yyyy/mm/dd", week_start: 0 })
Country.create({ country_code: "KR", name: "Korea, Republic of", date_format: "yyyy/mm/dd", week_start: 0 })
Country.create({ country_code: "KW", name: "Kuwait", date_format: "dd/mm/yyyy", week_start: 6 })
Country.create({ country_code: "KG", name: "Kyrgyzstan", date_format: "dd.mm.yyyy", week_start: 1 })
Country.create({ country_code: "LA", name: "Lao People's Democratic Republic", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "LV", name: "Latvia", date_format: "dd.mm.yyyy", week_start: 1 })
Country.create({ country_code: "LB", name: "Lebanon", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "LS", name: "Lesotho", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "LR", name: "Liberia", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "LY", name: "Libya", date_format: "dd/mm/yyyy", week_start: 6 })
Country.create({ country_code: "LI", name: "Liechtenstein", date_format: "dd.mm.yyyy", week_start: 1 })
Country.create({ country_code: "LT", name: "Lithuania", date_format: "yyyy-mm-dd", week_start: 1 })
Country.create({ country_code: "LU", name: "Luxembourg", date_format: "dd.mm.yyyy", week_start: 1 })
Country.create({ country_code: "MO", name: "Macao", date_format: "dd/mm/yyyy", week_start: 0 })
Country.create({ country_code: "MK", name: "Macedonia, Republic of", date_format: "dd.mm.yyyy", week_start: 1 })
Country.create({ country_code: "MG", name: "Madagascar", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "MW", name: "Malawi", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "MY", name: "Malaysia", date_format: "dd mmm yyyy", week_start: 1 })
Country.create({ country_code: "MV", name: "Maldives", date_format: "yy/mm/dd", week_start: 1 })
Country.create({ country_code: "ML", name: "Mali", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "MT", name: "Malta", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "MH", name: "Marshall Islands", date_format: "mm/dd/yyyy", week_start: 1 })
Country.create({ country_code: "MQ", name: "Martinique", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "MR", name: "Mauritania", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "MU", name: "Mauritius", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "YT", name: "Mayotte", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "MX", name: "Mexico", date_format: "dd/mm/yyyy", week_start: 0 })
Country.create({ country_code: "FM", name: "Micronesia, Federated States of", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "MD", name: "Moldova, Republic of", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "MC", name: "Monaco", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "MN", name: "Mongolia", date_format: "yyyy-mm-dd", week_start: 1 })
Country.create({ country_code: "ME", name: "Montenegro", date_format: "d.m.yyyy", week_start: 1 })
Country.create({ country_code: "MS", name: "Montserrat", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "MA", name: "Morocco", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "MZ", name: "Mozambique", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "MM", name: "Myanmar", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "NA", name: "Namibia", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "NR", name: "Nauru", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "NP", name: "Nepal", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "NL", name: "Netherlands", date_format: "dd-mm-yyyy", week_start: 1 })
Country.create({ country_code: "NC", name: "New Caledonia", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "NZ", name: "New Zealand", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "NI", name: "Nicaragua", date_format: "dd/mm/yyyy", week_start: 0 })
Country.create({ country_code: "NE", name: "Niger", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "NG", name: "Nigeria", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "NU", name: "Niue", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "NF", name: "Norfolk Island", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "MP", name: "Northern Mariana Islands", date_format: "mm/dd/yyyy", week_start: 1 })
Country.create({ country_code: "NO", name: "Norway", date_format: "dd.mm.yyyy", week_start: 1 })
Country.create({ country_code: "OM", name: "Oman", date_format: "dd/mm/yyyy", week_start: 6 })
Country.create({ country_code: "PK", name: "Pakistan", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "PW", name: "Palau", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "PS", name: "Palestine, State of", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "PA", name: "Panama", date_format: "dd/mm/yyyy", week_start: 0 })
Country.create({ country_code: "PG", name: "Papua New Guinea", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "PY", name: "Paraguay", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "PE", name: "Peru", date_format: "dd/mm/yyyy", week_start: 0 })
Country.create({ country_code: "PH", name: "Philippines", date_format: "mm/dd/yyyy", week_start: 0 })
Country.create({ country_code: "PN", name: "Pitcairn", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "PL", name: "Poland", date_format: "dd.mm.yyyy", week_start: 1 })
Country.create({ country_code: "PT", name: "Portugal", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "PR", name: "Puerto Rico", date_format: "mmm d, yyyy", week_start: 0 })
Country.create({ country_code: "QA", name: "Qatar", date_format: "dd/mm/yyyy", week_start: 6 })
Country.create({ country_code: "RE", name: "Réunion", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "RO", name: "Romania", date_format: "dd.mm.yyyy", week_start: 1 })
Country.create({ country_code: "RU", name: "Russian Federation", date_format: "dd.mm.yyyy", week_start: 1 })
Country.create({ country_code: "RW", name: "Rwanda", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "BL", name: "Saint Barthélemy", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "SH", name: "Saint Helena, Ascension and Tristan da Cunha", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "KN", name: "Saint Kitts and Nevis", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "LC", name: "Saint Lucia", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "MF", name: "Saint Martin (French part)", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "PM", name: "Saint Pierre and Miquelon", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "VC", name: "Saint Vincent and the Grenadines", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "WS", name: "Samoa", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "SM", name: "San Marino", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "ST", name: "Sao Tome and Principe", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "SA", name: "Saudi Arabia", date_format: "dd/mm/yyyy", week_start: 6 })
Country.create({ country_code: "SN", name: "Senegal", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "RS", name: "Serbia", date_format: "d.m.yyyy", week_start: 1 })
Country.create({ country_code: "SC", name: "Seychelles", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "SL", name: "Sierra Leone", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "SG", name: "Singapore", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "SX", name: "Sint Maarten (Dutch part)", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "SK", name: "Slovakia", date_format: "dd.mm.yyyy", week_start: 1 })
Country.create({ country_code: "SI", name: "Slovenia", date_format: "d. mm. yyyy", week_start: 1 })
Country.create({ country_code: "SB", name: "Solomon Islands", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "SO", name: "Somalia", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "ZA", name: "South Africa", date_format: "dd mmm yyyy", week_start: 0 })
Country.create({ country_code: "GS", name: "South Georgia and the South Sandwich Islands", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "SS", name: "South Sudan", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "ES", name: "Spain", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "LK", name: "Sri Lanka", date_format: "yyyy-mm-dd", week_start: 1 })
Country.create({ country_code: "SD", name: "Sudan", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "SR", name: "Suriname", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "SJ", name: "Svalbard and Jan Mayen", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "SZ", name: "Swaziland", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "SE", name: "Sweden", date_format: "d/m yyyy", week_start: 1 })
Country.create({ country_code: "CH", name: "Switzerland", date_format: "dd.mm.yyyy", week_start: 1 })
Country.create({ country_code: "SY", name: "Syrian Arab Republic", date_format: "dd/mm/yyyy", week_start: 6 })
Country.create({ country_code: "TW", name: "Taiwan", date_format: "yyyy/m/d", week_start: 0 })
Country.create({ country_code: "TJ", name: "Tajikistan", date_format: "dd.mm.yyyy", week_start: 1 })
Country.create({ country_code: "TZ", name: "Tanzania, United Republic of", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "TH", name: "Thailand", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "TL", name: "Timor-Leste", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "TG", name: "Togo", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "TK", name: "Tokelau", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "TO", name: "Tonga", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "TT", name: "Trinidad and Tobago", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "TN", name: "Tunisia", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "TR", name: "Turkey", date_format: "dd.mm.yyyy", week_start: 1 })
Country.create({ country_code: "TM", name: "Turkmenistan", date_format: "dd.mm.yyyy", week_start: 1 })
Country.create({ country_code: "TC", name: "Turks and Caicos Islands", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "TV", name: "Tuvalu", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "UG", name: "Uganda", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "UA", name: "Ukraine", date_format: "dd.mm.yyyy", week_start: 1 })
Country.create({ country_code: "AE", name: "United Arab Emirates", date_format: "dd/mm/yyyy", week_start: 6 })
Country.create({ country_code: "GB", name: "United Kingdom", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "UM", name: "United States Minor Outlying Islands", date_format: "mm/dd/yyyy", week_start: 0 })
Country.create({ country_code: "US", name: "United States", date_format: "mm/dd/yyyy", week_start: 0 })
Country.create({ country_code: "UY", name: "Uruguay", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "UZ", name: "Uzbekistan", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "VU", name: "Vanuatu", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "VE", name: "Venezuela, Bolivarian Republic of", date_format: "dd/mm/yyyy", week_start: 0 })
Country.create({ country_code: "VN", name: "Viet Nam", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "VG", name: "Virgin Islands, British", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "VI", name: "Virgin Islands, U.S.", date_format: "mm/dd/yyyy", week_start: 1 })
Country.create({ country_code: "WF", name: "Wallis and Futuna", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "EH", name: "Western Sahara", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "YE", name: "Yemen", date_format: "dd/mm/yyyy", week_start: 6 })
Country.create({ country_code: "ZM", name: "Zambia", date_format: "dd/mm/yyyy", week_start: 1 })
Country.create({ country_code: "ZW", name: "Zimbabwe", date_format: "dd/mm/yyyy", week_start: 0 })